### ISSUE TITLE
Update status on push

### ISSUE THREAD

**Issue by sixmen** [ouzi-dev/commit-status-updater#192]
I'm using GitHub Actions on push also.
And I have some data to want to set as status of master commit-ish.

Do you have a plan to support to update status on push event?

**Comment by belitre** [comment]
Hi @sixmen 

First sorry for the delay! With all the covid-19 stuff, and holidays... I didn't see the issue :(

The plugin is designed to work with pull requests, and there are no plans to change it to use with the push event, sorry about that.

Cheers!
